version: "3.8"

services:
  backend:
    image: notify-backend
    restart: always
    build: ./
    command: node server.js 
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    restart: always
    ports:
      - "21027:21027"
    volumes:
      - notify-vol:/data/db

volumes:
  notify-vol:

